/* Generated by JTB 1.4.11 */
package foo.syntaxtree;

import foo.visitor.*;

public class MyInteger implements INode {

  public NodeToken f0;

  private static final long serialVersionUID = 1411L;

  public MyInteger(final NodeToken n0) {
    f0 = n0;
  }

  @Override
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  @Override
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  @Override
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  @Override
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
