/* Generated by JTB 1.4.11 */
package foo.syntaxtree;

import foo.visitor.IRetArguVisitor;
import foo.visitor.IRetVisitor;
import foo.visitor.IVoidArguVisitor;
import foo.visitor.IVoidVisitor;

public class NodeChoice implements INode {

  public INode choice;

  public int which;

  public int total;

  private static final long serialVersionUID = 1411L;

  public NodeChoice(final INode node) {
   this(node, -1, -1);
  }

  public NodeChoice(final INode node, final int whichChoice, final int totalChoices) {
    choice = node;
    which = whichChoice;
    total = totalChoices;
  }

  @Override
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return choice.accept(vis, argu);
  }

  @Override
  public <R> R accept(final IRetVisitor<R> vis) {
    return choice.accept(vis);
  }

  @Override
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    choice.accept(vis, argu);
  }

  @Override
  public void accept(final IVoidVisitor vis) {
    choice.accept(vis);
  }

}
