/* Generated by JTB 1.4.11 */
package foo.visitor;

import foo.syntaxtree.*;

public interface IRetVisitor<R> {

  public R visit(final NodeChoice n);

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeTCF n);

  public R visit(final NodeToken n);

  public R visit(final Start n);

  public R visit(final Expression n);

  public R visit(final AdditiveExpression n);

  public R visit(final MultiplicativeExpression n);

  public R visit(final UnaryExpression n);

  public R visit(final Identifier n);

  public R visit(final MyInteger n);

}
