/* Generated by JTB 1.4.11 */
package foo.visitor;

import foo.syntaxtree.*;

public interface IRetArguVisitor<R, A> {

  public R visit(final NodeChoice n, final A argu);

  public R visit(final NodeList n, final A argu);

  public R visit(final NodeListOptional n, final A argu);

  public R visit(final NodeOptional n, final A argu);

  public R visit(final NodeSequence n, final A argu);

  public R visit(final NodeTCF n, final A argu);

  public R visit(final NodeToken n, final A argu);

  public R visit(final Start n, final A argu);

  public R visit(final Expression n, final A argu);

  public R visit(final AdditiveExpression n, final A argu);

  public R visit(final MultiplicativeExpression n, final A argu);

  public R visit(final UnaryExpression n, final A argu);

  public R visit(final Identifier n, final A argu);

  public R visit(final MyInteger n, final A argu);

}
