/* Generated by JTB 1.4.11 */
package foo.visitor;

import foo.syntaxtree.*;

public interface IVoidVisitor {

  public void visit(final NodeChoice n);

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeTCF n);

  public void visit(final NodeToken n);

  public void visit(final Start n);

  public void visit(final Expression n);

  public void visit(final AdditiveExpression n);

  public void visit(final MultiplicativeExpression n);

  public void visit(final UnaryExpression n);

  public void visit(final Identifier n);

  public void visit(final MyInteger n);

}
