/* Generated by JTB 1.4.11 */
package foo.visitor;

import foo.syntaxtree.*;

public interface IVoidArguVisitor<A> {

  public void visit(final NodeChoice n, final A argu);

  public void visit(final NodeList n, final A argu);

  public void visit(final NodeListOptional n, final A argu);

  public void visit(final NodeOptional n, final A argu);

  public void visit(final NodeSequence n, final A argu);

  public void visit(final NodeTCF n, final A argu);

  public void visit(final NodeToken n, final A argu);

  public void visit(final Start n, final A argu);

  public void visit(final Expression n, final A argu);

  public void visit(final AdditiveExpression n, final A argu);

  public void visit(final MultiplicativeExpression n, final A argu);

  public void visit(final UnaryExpression n, final A argu);

  public void visit(final Identifier n, final A argu);

  public void visit(final MyInteger n, final A argu);

}
